Fix/improve language
beemdevelopment/website pull request #12
Opened 2023-02-27 22:40 UTC by salim-b

2023-05-02 15:13 UTC, kurtmckee requested changes
I think several of the changes here look good, but a few should be removed.

2023-05-02 15:13 UTC, kurtmckee commented on layouts/index.html
> +                  malicious intents gets a hold of the vault file, it’s
I think that "intent" is correct here.

2023-05-02 15:13 UTC, kurtmckee commented on layouts/index.html
> +                  Set a custom icon for an entry to make it easier to find it.
"it" does not need to be added here; the entry is already referenced by "make _it_ easier to find".

2024-04-28 14:35 UTC, alexbakker commented
Thanks, but these changes are no longer relevant for the redesign of the website.

2024-04-28 14:35 UTC, closed without merging